#!/usr/bin/env python

blkt = {}

def 50():
	blkt['description'] = 'Station Identifier Blockette'
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	return blkt

def 52():
	blkt['description'] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	return blkt

def 53():
	blkt['description'] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	return blkt

def 54():
	blkt['description'] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	return blkt

def 57():
	blkt['description'] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	return blkt

def 58():
	blkt['description'] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	return blkt

def 59():
	blkt['description'] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	return blkt

def 62():
	blkt['description'] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	blkt[''] = ''
	return blkt